import { Geist, Geist_Mono } from "next/font/google";
import { Slackey } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const slack = Slackey({
  variable: "--font-slackey",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "The Spot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${slack.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
